spring.application.name=ejercicio10

spring.datasource.url=jdbc:postgresql://dpg-d7oa6dqpmmbs73d1fd10-a.oregon-postgres.render.com:5432/dbejercicio10
spring.datasource.username=dbejercicio10_user
spring.datasource.password=JuQ9kjC8gNWlaPdkPx514IvAahdcUm0x

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true